BEGIN TRANSACTION;
CREATE TABLE Employees2(ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, FName TEXT NOT NULL, LName TEXT NOT NULL, Age INTEGER NOT NULL, Address TEXT, Salary REAL, HireDate TEXT, 'Image' BLOB DEFAULT NULL);
INSERT INTO "Employees2" VALUES(1,'Shaun','Miller',41,'121 Main St',500000.0,'2018-04-03',NULL);
DELETE FROM "sqlite_sequence";
INSERT INTO "sqlite_sequence" VALUES('Employees2',1);
COMMIT;
